### Module 4 - Numpy Case Study


In [1]:
import numpy as np

```
1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
value and returns a NumPy array of the given dimension filled with the
given value e.g.: solve((3, 3), 5) will return
[
[5, 5, 5],
[5, 5, 5],
[5, 5, 5]
]
```


In [2]:
def solve(shape, n):
    return np.full(shape, n)


solve((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

2. Create a method that takes n NumPy arrays of the same dimensions,
   sums them and returns the answer.


In [7]:
def sum_arr(*args):
    try:
        return sum(np.array(arg) for arg in args)
    except Exception:
        print("Error")


sum_arr([12, 232, 3, 3], [123, 123, 223, 456])

array([135, 355, 226, 459])

```
3. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
top-left N X M sub matrix, e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
top_left_sub_matrix (matrix, 2, 2) -> should return:
[
[1, 2]
[4, 5]
]
```


In [14]:
def get_sub_arr(arr, n, m):
    return arr[0:n, 0:m]


arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
get_sub_arr(arr, 2, 2)

array([[1, 2],
       [4, 5]])

```
4. Given a 2 D Array of N X M Dimension, write a function that accepts this
array as well as two numbers N and M. The method should return the
bottom-right N X M sub matrix, e.g:
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are
zero indexed)
[
[5, 6]
[8, 9]
]
```


In [17]:
def get_sub_arr(arr, n, m):
    return arr[-n:, -m:]


arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
get_sub_arr(arr, 2, 2)

array([[5, 6],
       [8, 9]])

```
5. Given a 1 D NumPy Array. Write a function that accepts this array as
parameters. The method should return a dictionary with 'mean' and
'std_dev' as key and array's mean and array's standard deviation as
values:
[1, 1, 1]
solution(arr) -> should return :
{'mean': 1.0, 'std_dev': 0.0}
```


In [20]:
def solution(arr):
    return {'mean': np.mean(arr), 'std_dev': np.std(arr)}


solution(np.ones(3))

{'mean': 1.0, 'std_dev': 0.0}