### Module 4 - Numpy Assignment


1. Create a 3x3 matrix array with values ranging from 2 to 10.


In [4]:
import numpy as np

In [2]:
arr = np.random.randint(2, 10, (3, 3))
arr

array([[4, 7, 6],
       [5, 3, 9],
       [8, 8, 8]])

```
2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
```


In [11]:
original_arr = [1, 2, 3, 4]
float_arr = np.array(original_arr, dtype='float32')
type(float_arr)
float_arr.dtype

dtype('float32')

```
3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
```


In [19]:
og_arr = np.array([10, 20, 30])
res = np.append(og_arr, [50, 60, 70, 80, 90])
res

array([10, 20, 30, 50, 60, 70, 80, 90])

4. Create two NumPy arrays and add the elements of both the arrays and
   store the result in sumArray.


In [22]:
a = np.array([[1, 2], [1, 2]])
b = np.array([[1, 2], [1, 2]])
sumArray = a+b
sumArray

array([[2, 4],
       [2, 4]])

```
5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
   in array1
   Perform the following tasks:
   a. Extract the 1st row from the array
   b. Extract the last element from the array.
```


In [27]:
arr=np.arange(10,100,10).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [29]:
arr[0,:]

array([10, 20, 30])

In [47]:
a=arr[-1:,-1:][0][0]
a

90